name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Python and Poetry
      - name: Set up Python and Poetry
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # Install Poetry and set the PATH
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # Install dependencies using Poetry
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      # Debug directory (optional for troubleshooting)
      - name: Debug directory
        run: ls -R

      # Run the tests
      - name: Run tests
        run: poetry run pytest -v
